### ISSUE TITLE
Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read'

### ISSUE THREAD

**Issue by ecchi** [thejinx0r/node-gdrive-fuse#32]
Mac 10.10.1
Pulled latest commit 84161e9b57. installed concurrencykit (brew)
Deleted cache, and node_modules, re-did npm install, tweaked config.json to include new "refreshDelay": 60000

coffee fs.coffee, everything seems to mount fine. Browsing the mount is quick and responsive.
Tried opening a media file 
...
Eventually media player(s) fail.

```
2014-12-30T19:32::29 - info: mount point: /Users/ecchi/tmp/mnt
error
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
error
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
error
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
2014-12-30T19:36::0 - error: there was an error downloading file
2014-12-30T19:36::0 - error:  code=ECONNRESET, sslError=undefined
error
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
2014-12-30T19:36::52 - error: there was an error downloading file
2014-12-30T19:36::52 - error:  code=ECONNRESET, sslError=undefined
error
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }

TypeError: Cannot read property 'id' of undefined
```

**Comment by thejinx0r** [comment]
What version of node are you using?

**Comment by martinbowling** [comment]
``
2015-1-4T21:27::0 - info: mount point: /Users/martinbowling/Downloads/gdrive
error
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: null == true
  at TLSSocket.socketOnData (_http_client.js:307:3)
  at TLSSocket.emit (events.js:107:17)
  at TLSSocket.Readable.read (_stream_readable.js:372:10)
  at TLSSocket.socketCloseListener (_http_client.js:228:10)
  at TLSSocket.emit (events.js:129:20)
  at TCP.close (net.js:461:12)
`` 

commit c45c852d7932f7d0e1ff26876d9dbabf2f6931c8

OS X 10.8.5

node v0.11.14

**Comment by thejinx0r** [comment]
It's related.

It seems like the issue is occuring more frequently on node 0.11 than on node 0.10, so it's one of the issues that is next on my issue list.

**Comment by martinbowling** [comment]
any movement on this particular issue? anything I can do to help out.

**Comment by thejinx0r** [comment]
I haven't been able to figure it out.
I've been using io.js instead of node.js and it seems better now.

**Comment by martinbowling** [comment]
is there a repo with the io.js version?

**Comment by thejinx0r** [comment]
You just need to install iojs. Iojs should be a drop in replacement of nodejs. 

When you install iojs, it should symlink node to Iojs 



Eric

**Comment by thejinx0r** [comment]
might be related to #57
