### ISSUE TITLE
filesystem information does not update properly

### ISSUE THREAD

**Issue by dellipse** [thejinx0r/node-gdrive-fuse#39]
I am noticing items that should NOT be getting updated are showing up in the log as updated in Google Drive, but items that SHOULD be getting updated (new items from outside sources) are not showing up after well over an hour using the default settings for refresh rate.

**Comment by thejinx0r** [comment]
I'll check this again.
It was working for me, but maybe I need a different test case.

For files that " should NOT be getting updated", are you sure that those are not new files that were recently uploaded to GDrive and that google is maybe accessing those files to convert it?
Simply accessing a file or folder on google drive can cause a file to be updated (notably, the last date accessed field).

**Comment by dellipse** [comment]
That could be the case for files that are "updated" when something is just accessed.

However, after over 24 hours, it still has not detected a folder and its associated contents that were added by another client.

**Comment by wnielson** [comment]
I am observing similar behavior and I believe I have identified the issue.  In the function `parseChanges` ([here](https://github.com/thejinx0r/node-gdrive-fuse/blob/master/src/client.coffee#L287)), it appears that the parent items are not being updated to include the new child element.
