### ISSUE TITLE
Linux 'cp' command copies 8519680 bytes, then stops downloading

### ISSUE THREAD

**Issue by dellipse** [thejinx0r/node-gdrive-fuse#41]
It appears that the Linux 'cp' command is not downloading files well anymore.

When I try to copy a file to a LOCAL file system, it copies the first 8519680 bytes, then stops transferring any data, even though the command is still waiting for the transfer to complete.  It will sit there for hours without error, but no network activity related to the transfer occurs.

Uploads TO Google Drive still appear to be working properly, just FROM Google Drive to local storage seems to be the issue.

**Comment by thejinx0r** [comment]
I can't reproduce it.
Is it all files, or just one?

**Comment by dellipse** [comment]
Testing now....

**Comment by dellipse** [comment]
Still happening with latest pull
