### ISSUE TITLE
Seems to have completely stopped working?

### ISSUE THREAD

**Issue by Rick7C2** [thejinx0r/node-gdrive-fuse#49]
I had this working great on a VPS no issues what so ever. About 22 hours later the mount failed. 

When listing the mount dir I got "transport endpoint is not connected"

So I rebooted vps and ran sudo coffee fs.coffee.  Everything looked normal but when listing the mount dir there was nothing there.

Rebooted again. rm -rf cache dir then coffee fs.coffee says its downloading folders from google.

Checked mound dir nothing. checked /cache/data and nothing. Still not working.

Whats going on?

**Comment by wnielson** [comment]
I have been using this for months and also just noticed today that it no longer works.  When running `coffee fs.coffee` I get the error:

    Access Token Set
    2015-3-9T15:22::19 - info: Downloading full folder structure from google
    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: ENOSPC, write
