### ISSUE TITLE
node and node-gyp mismatch

### ISSUE THREAD

**Issue by ger08061959** [thejinx0r/node-gdrive-fuse#50]
Trying to compile and install gives:

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"

Followed by:

npm ERR! weird error 1
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ger/node-gdrive-fuse/node_modules/mmmagic
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"

gyp ERR! cwd /home/ger/node-gdrive-fuse/node_modules/fusejs
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"

Which might be caused by version differences. But not able to find a node v0.10.10 to match th gyp version. Or am I wrong in my interpretation.

**Comment by thejinx0r** [comment]
What step where you at?
