### ISSUE TITLE
downloads on ubuntu do not work

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#54]
I'm using the latest commit, and downloads/copy does not work on ubuntu - works on osx.

Upload works fine on ubuntu.

Here's the log from a download attempt:

{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.571Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-0-8388607","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.571Z"}
{"level":"debug","message":"starting to download 12 Monkeys - S01E01 - Splinter WEBDL-1080p.mkv, chunkStart: 0","timestamp":"2015-04-30T16:15:39.572Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.623Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-1962934272-1970016294","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.623Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.625Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-25165824-33554431","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.625Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.625Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-33554432-41943039","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.625Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.626Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-41943040-50331647","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.626Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.629Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-8388608-16777215","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.629Z"}
{"level":"debug","message":"there was an debug stat-ing a file in file.open","timestamp":"2015-04-30T16:15:39.629Z"}
{"errno":-2,"code":"ENOENT","path":"/mnt/2TB1/cache/download/0B_SCJY8yONoyalh4QWFDZldtRGs-16777216-25165823","level":"debug","message":"","timestamp":"2015-04-30T16:15:39.629Z"}
{"level":"debug","message":"updating url for 12 Monkeys - S01E01 - Splinter WEBDL-1080p.mkv","timestamp":"2015-04-30T16:15:41.869Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.871Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.871Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.880Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.880Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.883Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.883Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.917Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.918Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.920Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.920Z"}
{"level":"debug","message":"There was an error during recursive download:","timestamp":"2015-04-30T16:15:41.928Z"}
{"level":"debug","message":"expiredUrl","timestamp":"2015-04-30T16:15:41.928Z"}
{"level":"debug","message":"Getting changes from Google Drive. The last change id was 146731.","timestamp":"2015-04-30T16:15:57.608Z"}

After that it does nothing....nothing is transfered.

**Comment by saqebakhter** [comment]
There are no apparent errors other than rsync/cp being stalled forever. And no mentions of downloading in the logs other than what I posted above - the same code works on OSX -- i tried this with ubuntu 14.10, and 140.04 - no success.

Has anyone been able to use the later releases with ubuntu successfully?

Uploading works great though - for the most part.

**Comment by saqebakhter** [comment]
It looks like the first 5 chunks download - but after that the download stalls.

**Comment by thejinx0r** [comment]
That's weird.
You are not the first person to report this, but I also I am not if I can reproduce since I don't have access to ubuntu machine right now.

**Comment by saqebakhter** [comment]
I can give you access to my VPS where is is occurring if you need. I've 
tried to debug it very unsuccessfully so far.

> thejinx0r <mailto:notifications@github.com>
> May 4, 2015 at 2:11 PM
>
> That's weird.
> You are not the first person to report this, but I also I am not if I 
> can reproduce since I don't have access to ubuntu machine right now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/54#issuecomment-98850943>.
>

-- 
--Saqeb

**Comment by thejinx0r** [comment]
Sure, you have my email address in the package.json. it's eric at ericyen
dot com


  Eric

**Comment by saqebakhter** [comment]
Emailed you the access details - thanks.

> thejinx0r <mailto:notifications@github.com>
> May 4, 2015 at 2:20 PM
> Sure, you have my email address in the package.json. it's eric at ericyen
> dot com
>
>
> Eric
>
> On Mon, May 4, 2015 at 5:17 PM, saqebakhter <notifications@github.com>
> wrote:
>
> > I can give you access to my VPS where is is occurring if you need. I've
> > tried to debug it very unsuccessfully so far.
> >
> > > thejinx0r <mailto:notifications@github.com>
> > > May 4, 2015 at 2:11 PM
> > >
> > > That's weird.
> > > You are not the first person to report this, but I also I am not if I
> > > can reproduce since I don't have access to ubuntu machine right now.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> https://github.com/thejinx0r/node-gdrive-fuse/issues/54#issuecomment-98850943
> > >.
> > >
> >
> > --
> > --Saqeb
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/54#issuecomment-98851939>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/54#issuecomment-98852427>.
>

-- 
--Saqeb
