### ISSUE TITLE
unhandled error event

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#57]
Had almost 2 days of uptime until this crash:

2015-5-19T21:52::23 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::23 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::23 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::25 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::25 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::26 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::26 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::26 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T21:52::26 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T21:52::28 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:52::28 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-19T21:56::48 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T21:56::48 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T21:57::26 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T21:57::26 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:1::48 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:1::48 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:2::7 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:2::7 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:2::7 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:2::7 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:3::49 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:3::49 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:5::4 - ^[[32minfo^[[39m: Starting to upload file Taken 2 (2012)-trailer.mov
2015-5-19T22:5::6 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:5::6 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-19T22:5::11 - ^[[31merror^[[39m: There was an error with getting a new resumable link
2015-5-19T22:5::11 - ^[[31merror^[[39m:  errors=[domain=global, reason=authError, message=Invalid Credentials, locationType=header, location=Authorization], code=401, message=Invalid Credentials
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: EMFILE: too many open files, open '/mnt/2TB1/cache/upload/6e0a025498f8dc2c47290578f69d7809'
  at Error (native)

**Comment by thejinx0r** [comment]
It should be fixed. 
The other thing is, maybe you could try switching to [io.js](http://iojs.org)? It should work with all versions of iojs. (you would need to reinstall the npm modules.)

**Comment by saqebakhter** [comment]
Hey

Thanks for fixing - I'm already using iojs - currently using 1.8.1 - 
should I move to 2.x ?

> thejinx0r <mailto:notifications@github.com>
> May 20, 2015 at 8:14 AM
>
> It should be fixed.
> The other thing is, maybe you could try switching to io.js 
> <http://iojs.org>? It should work with all versions of iojs. (you 
> would need to reinstall the npm modules.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/57#issuecomment-103860631>.
>

-- 
--Saqeb

**Comment by thejinx0r** [comment]
Nevermind, I take it back, it's not fixed, I just got the same error.

**Comment by saqebakhter** [comment]
:( thanks for trying  ! I'm sure you'll get it haha.

> thejinx0r <mailto:notifications@github.com>
> May 20, 2015 at 8:25 AM
>
> Nevermind, I take it back, it's not fixed, I just got the same error.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/57#issuecomment-103862277>.
>

-- 
--Saqeb

**Comment by saqebakhter** [comment]
Okay I've switched to 2.x iojs.

**Comment by saqebakhter** [comment]
On the latest commit 56c6744f1395ab5353c6ef00c55fcf29cf7381c0

Still getting this error:


2015-5-21T15:31::6 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-21T15:31::6 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-21T15:31::19 - ^[[31merror^[[39m: error after piping code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-21T15:31::19 - ^[[31merror^[[39m:  code=ECONNRESET, errno=ECONNRESET, syscall=read
2015-5-21T15:31::34 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-21T15:31::34 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-21T15:31::35 - ^[[31merror^[[39m: error after piping code=EPIPE, errno=EPIPE, syscall=write, address=undefined
2015-5-21T15:31::35 - ^[[31merror^[[39m:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: EMFILE: too many open files, open '/mnt/2TB1/cache/upload/cfb1f6b51554fc1ec30f21a4a8359344'
  at Error (native)

**Comment by thejinx0r** [comment]
I've tracked down the error to file downloading.
There's a leak going on there with the streams.

**Comment by saqebakhter** [comment]
Cool is the fix checked in ? I'll update to the latest and keep testing.

**Comment by thejinx0r** [comment]
I don't have a proper fix yet. I keep getting closer.

**Comment by thejinx0r** [comment]
This is fixed. I found the leak that caused the "EMFILE".

**Comment by thejinx0r** [comment]
I've switched to a linux based os from OS X and the performance is great.
I'm now using 1mb chunks and 4 advanced chunks and it's surprisingly keeps up.

And on linux, the default setting for fuse is to run on multithread and on OS X, it's single threaded.
I think that's what was causing a lot of the problems that I wasn't getting before.

**Comment by saqebakhter** [comment]
Could you share your config.json settings?

**Comment by thejinx0r** [comment]
```
{
  "debug": true,
  "clientId": "520595891712-ofd914r711g7cuq8uofet8ekf7mneo2g.apps.googleusercontent.com",
  "clientSecret": "dzxWOFdSUtT7RL8bvrVMOK9t",
  "mountPoint": "/Users/eric/GDrive",
  "chunkSize": 1048576,
  "refreshDelay": 300000,
  "advancedChunks": 4,
  "maxCacheSize": 870400,
  "cacheLocation": "/GDrive/.gdrive",
  "maxConcurrentUploads": 4,
 }
```

Without the access token, this is my config file
