### ISSUE TITLE
/tmp/cache/{download/upload} consume all disk space

### ISSUE THREAD

**Issue by jruels** [thejinx0r/node-gdrive-fuse#61]
Hello,
First I wanted to say I really appreciate all the work you've put in to get this working! 
I've got watch.coffee running but it does not clean up /tmp/cache or stop it from consuming 100% of disk space. 

Is there something I'm missing? 

Thanks!

**Comment by thejinx0r** [comment]
There have been some updates.
The watch.coffee has been deleted now and merged in to fs.coffee

Have you set the "maxCacheSize" in the config.json file?
What have you set yours too?
Just remember, the maxCacheSize is in mega bytes.

**Comment by jruels** [comment]
Thanks! I fixed it.  Didn't realize it was set so large by default. Are the cache directories ever cleaned up?

**Comment by thejinx0r** [comment]
Yes, in the current version, it should clean it up once the cache size hits up to about 80%.
It doesn't check the upload anymore, but I hopefully, it won't be a problem.

**Comment by dellipse** [comment]
Upload could become an issue for me as well since I upload a bunch with
this tool. More so than downloads, actually.

**Comment by thejinx0r** [comment]
Does your upload bottle neck? Or does the amount you upload at a time ever surpass your cache?

Because if the answer is no to those two questions, then I wouldn't worry.
Once a file has been uploaded, it is moved to the download folder.

**Comment by dellipse** [comment]
In that case I should be fine. I haven't had upload issues for a while, but
downloads have been "fun" for a while. I'll pull the latest code today and
stop using watch.coffee. I'll also check the Ubuntu Upstart directions and
correct them if needed.
