### ISSUE TITLE
after crash - file uploading does not resume

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#66]
015-6-23T15:27::18 - error:  code=EPIPE, errno=EPIPE, syscall=write, address=undefined
dns.js:82
    this.callback(null, addresses[0], addresses[0].indexOf(':') >= 0 ? 6 : 4);
                                                  ^
TypeError: Cannot read property 'indexOf' of undefined
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:51)

stdin: is not a tty
node: no process found
2015-6-23T15:27::49 - info: loading upload tree
Access Token Set
2015-6-23T15:27::49 - info: Loading folder structure
2015-6-23T15:27::49 - info: Opened a connection to the database
{ id: '0B_SCJY8yONoyaVZMTHB3YXJzUzQ',
  parentid: '0B_SCJY8yONoySnZER04zLXUxX3c',
  name: 'Season 1',
  ctime: 1434991395242,
  mtime: 1434991395174,
  inode: 5419,
  permission: true,
  children: [ 5446, 5447, 5448 ],
  mode: 16895 }
2015-6-23T15:27::51 - info: attempting to start f4js
2015-6-23T15:27::51 - error: unmount error: killed=false, code=32, signal=null, cmd=/bin/sh -c umount -f /mnt/2TB2/gdrivefs
2015-6-23T15:27::51 - info: mount point: /mnt/2TB2/gdrivefs
2015-6-23T15:27::59 - info: resuming file uploading

---Although it says resuming file uploading - it does not actually do anything.

**Comment by thejinx0r** [comment]
It could be that the only files that could be uploaded were not completed
transferred.
For example, if you are transferring a file from your hd to GDrive, and
then it crashes, such that only a partial file is transferred on to GDrive,
node-gdrive-fs won't try to upload it.

I'm currently working on porting the code from coffeescript to javascript
so that it will be easier to debug.
It seems like some of the problems (if not most) are related to not having
enough memory. And the reason you need a lot is that there's a memory leak
somewhere and I cannot find it using the normal nodejs debugger.


  Eric

**Comment by saqebakhter** [comment]
Hey

No the files were transferred completely to gdrive - it just had not 
started to upload them yet ( i.e they were in the cache )

I have lots of memory on my uprgade machine 16gb of RAM i think

Cool yeah coffeescript is hard to debug.


thejinx0r wrote:
> It could be that the only files that could be uploaded were not completed
> transferred.
> For example, if you are transferring a file from your hd to GDrive, and
> then it crashes, such that only a partial file is transferred on to 
> GDrive,
> node-gdrive-fs won't try to upload it.
>
> I'm currently working on porting the code from coffeescript to javascript
> so that it will be easier to debug.
> It seems like some of the problems (if not most) are related to not having
> enough memory. And the reason you need a lot is that there's a memory leak
> somewhere and I cannot find it using the normal nodejs debugger.
>
>
> Eric
>
> On Tue, Jun 23, 2015 at 3:55 PM, saqebakhter <notifications@github.com>
> wrote:
>
> > 015-6-23T15:27::18 - error: code=EPIPE, errno=EPIPE, syscall=write,
> > address=undefined
> > dns.js:82
> > this.callback(null, addresses[0], addresses[0].indexOf(':') >= 0 ? 6 
> : 4);
> > ^
> > TypeError: Cannot read property 'indexOf' of undefined
> > at GetAddrInfoReqWrap.onlookup as oncomplete
> >
> > stdin: is not a tty
> > node: no process found
> > 2015-6-23T15:27::49 - info: loading upload tree
> > Access Token Set
> > 2015-6-23T15:27::49 - info: Loading folder structure
> > 2015-6-23T15:27::49 - info: Opened a connection to the database
> > { id: '0B_SCJY8yONoyaVZMTHB3YXJzUzQ',
> > parentid: '0B_SCJY8yONoySnZER04zLXUxX3c',
> > name: 'Season 1',
> > ctime: 1434991395242,
> > mtime: 1434991395174,
> > inode: 5419,
> > permission: true,
> > children: [ 5446, 5447, 5448 ],
> > mode: 16895 }
> > 2015-6-23T15:27::51 - info: attempting to start f4js
> > 2015-6-23T15:27::51 - error: unmount error: killed=false, code=32,
> > signal=null, cmd=/bin/sh -c umount -f /mnt/2TB2/gdrivefs
> > 2015-6-23T15:27::51 - info: mount point: /mnt/2TB2/gdrivefs
> > 2015-6-23T15:27::59 - info: resuming file uploading
> >
> > ---Although it says resuming file uploading - it does not actually do
> > anything.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/thejinx0r/node-gdrive-fuse/issues/66>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/66#issuecomment-114673390>.
>

-- 
--Saqeb

**Comment by thejinx0r** [comment]
this was fixed. in  443b8fb39ea7764e712f9f86e8865b2c9c73bd61 and d1f1530b42dd615ab0fe4966e63fe2ebc2f8dc17
