### ISSUE TITLE
JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by m3i58** [thejinx0r/node-gdrive-fuse#70]
Hi. Even though there is 10G+ memory available to the host instance node-gdrive-fuse fails with this error.

> 2015-9-5T9:53::9 - info: Parsing files
2015-9-5T9:53::49 - info: Taking a break from downloading files to try and parse files and folders. Current items to parse: 218950
2015-9-5T9:53::49 - info: Parinsg data, looking for root foolder
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)

Is there anything I can do about it? I will very much appreciate your help.

**Comment by thejinx0r** [comment]
You must have a really large amount of files. 

I will rewrite that section of the code so that it will use less memory

**Comment by m3i58** [comment]
Wow! That was fast. Thank you.

I've got hundreds of thousand small files, maybe that is the reason, but other tools were ok with it.

**Comment by thejinx0r** [comment]
this should be fixed now.
let me know if it doesn't work for you.

**Comment by m3i58** [comment]
Thank you, but now the nmp install failes :(

>npm ERR! fusejs@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fusejs@1.2.2 install script.
npm ERR! This is most likely a problem with the fusejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusejs
npm ERR! There is likely additional logging output above.

>npm ERR! System Linux 3.13.0-63-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/bq/node-gdrive-fuse
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by m3i58** [comment]
plus:
>In file included from ../src/filesystem.cc:11:0:
../src/mpsc_queue.h: In member function ‘uint mpsc_queue_t<T>::producer_publish(int64_t)’:
../src/mpsc_queue.h:154:8: error: ‘std::this_thread’ has not been declared
   std::this_thread::yield();          
        ^
make: *** [Release/obj.target/fusejs/src/filesystem.o] Error 1
make: Leaving directory `/home/user/node-gdrive-fuse/node_modules/fusejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node-gdrive-fuse/node_modules/fusejs
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by thejinx0r** [comment]
Can you try it again?
There is an update now for fusejs that should allow you to compile.
It was missing a compilation flag.

**Comment by m3i58** [comment]
I started fresh and used the master branch -->

npm install works fine, but then:

>File not found: /home/user/node-gdrive-fuse/src/client.coffee

Which is odd. Do you have any clues?
