### ISSUE TITLE
stuck in some loop?

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#72]
latest commit seem to get stuck in some sort of a loop ?

{"level":"debug","message":"saving folder tree","timestamp":"2015-09-07T17:41:38.961Z"}
{"level":"debug","message":"Starting to parse items from google.","timestamp":"2015-09-07T17:41:40.238Z"}
{"level":"debug","message":"There are 37976  items to parse and the current inodeTree size is 0.","timestamp":"2015-09-07T17:41:40.238Z"}
{"level":"info","message":"Parinsg data, looking for root foolder","timestamp":"2015-09-07T17:41:40.239Z"}
{"level":"info","message":"root node found","timestamp":"2015-09-07T17:41:40.239Z"}
{"level":"info","message":"Folders left to parse: 3029","timestamp":"2015-09-07T17:41:40.261Z"}
{"level":"info","message":"Folders left to parse: 1450","timestamp":"2015-09-07T17:41:40.269Z"}
{"level":"info","message":"Folders left to parse: 791","timestamp":"2015-09-07T17:41:40.272Z"}
{"level":"info","message":"Folders left to parse: 69","timestamp":"2015-09-07T17:41:40.274Z"}
{"level":"info","message":"Folders left to parse: 32","timestamp":"2015-09-07T17:41:40.275Z"}
{"level":"info","message":"Folders left to parse: 1","timestamp":"2015-09-07T17:41:40.276Z"}
{"level":"info","message":"Parsing files","timestamp":"2015-09-07T17:41:40.277Z"}
{"level":"debug","message":"After attempting to parse, there is 37977 items in the inodeTree and 0 items that were not yet parseable","timestamp":"2015-09-07T17:41:40.560Z"}
{"level":"info","message":"attempting to start f4js","timestamp":"2015-09-07T17:41:40.623Z"}
{"killed":false,"code":1,"signal":null,"cmd":"/bin/sh -c umount -f /mnt/gdrivefs","level":"error","message":"unmount error:","timestamp":"2015-09-07T17:41:40.641Z"}
{"level":"info","message":"mount point: /mnt/gdrivefs","timestamp":"2015-09-07T17:41:40.643Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-07T17:41:41.197Z"}
{"level":"info","message":"Access Token Set","timestamp":"2015-09-07T18:15:56.347Z"}
{"level":"debug","message":"Folder tree exist status: true","timestamp":"2015-09-07T18:15:56.357Z"}
{"level":"info","message":"Loading folder structure","timestamp":"2015-09-07T18:15:56.358Z"}
{"level":"info","message":"Opened a connection to the database","timestamp":"2015-09-07T18:15:56.360Z"}
{"level":"info","message":"attempting to start f4js","timestamp":"2015-09-07T18:15:57.029Z"}
{"killed":false,"code":1,"signal":null,"cmd":"/bin/sh -c umount -f /mnt/gdrivefs","level":"error","message":"unmount error:","timestamp":"2015-09-07T18:15:57.049Z"}
{"level":"info","message":"mount point: /mnt/gdrivefs","timestamp":"2015-09-07T18:15:57.052Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:54.222Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:54.497Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:54.680Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:54.928Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:55.136Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:55.365Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:55.587Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:55.776Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:56.014Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:56.217Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:56.414Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:56.604Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:56.849Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:57.144Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:57.377Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:57.570Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:57.746Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:57.967Z"}
{"level":"debug","message":"starting to download Gotham - S01E14 - The Fearsome Dr. Crane Bluray-720p.mkv, chunkStart: 0","timestamp":"2015-09-07T18:18:58.191Z"}

**Comment by thejinx0r** [comment]
Can you try downloading that file from the web portal?

**Comment by saqebakhter** [comment]
Restarted VPS - seems to be happening for a different file now - this one is downloadable via webportal - 

{"level":"debug","message":"After attempting to parse, there is 37977 items in the inodeTree and 0 items that were not yet parseable","timestamp":"2015-09-07T18:23:37.658Z"}
{"level":"info","message":"attempting to start f4js","timestamp":"2015-09-07T18:23:37.715Z"}
{"killed":false,"code":1,"signal":null,"cmd":"/bin/sh -c umount -f /home/sakhter/gdrivefs","level":"error","message":"unmount error:","timestamp":"2015-09-07T18:23:37.739Z"}
{"level":"info","message":"mount point: /home/sakhter/gdrivefs","timestamp":"2015-09-07T18:23:37.754Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-07T18:23:38.700Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:55.433Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:55.676Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:55.883Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:56.105Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:56.328Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:56.532Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:56.738Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:56.944Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:57.119Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:57.321Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:57.494Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:57.690Z"}
{"level":"debug","message":"starting to download Yeh Jawaani Hai Deewani.nfo, chunkStart: 0","timestamp":"2015-09-07T19:21:57.880Z"}
