### ISSUE TITLE
segfault 

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#74]
on latest 

2015-9-8T20:19::2 - info: adding a new file Star Wars Rebels - S01E07 - Gathering Forces Bluray-720p.mkv to folder Season 1
2015-9-8T20:20::48 - info: adding a new file Star Wars Rebels - S01E08 - Path of the Jedi Bluray-720p.mkv to folder Season 1
2015-9-8T20:21::16 - info: adding a new file Star Wars Rebels - S01E10 - Vision of Hope Bluray-720p.mkv to folder Season 1
/home/sakhter/gdrivejs.sh: line 15:  5654 Segmentation fault      (core dumped) node fs.es6.js

**Comment by thejinx0r** [comment]
What's the cpu on it? Mostly wondering if it's an AMD / Intel / Armv7.

**Comment by saqebakhter** [comment]
Intel Core i5 - this is my home desktop.

**Comment by thejinx0r** [comment]
can you run npm install again to update fusejs?
i turned off the part that would cause it to segfault.

**Comment by thejinx0r** [comment]
If this comes up again, please reopen this.
The problem was probably due to fusejs and it should be fixed now.
