### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#75]
Error when trying to upload

2015-9-9T23:48::29 - info: Starting to upload file Late Show with Stephen Colbert - 2015-09-08 - George Clooney, Jeb Bush, Jon Batiste and Stay Human HDTV-720p.mkv 
/root/node-gdrive-fuse/src/fs.es6.js:400
        for (childInode of parent.children) {
             ^
ReferenceError: childInode is not defined
    at GDriveFS.rmdir (/root/node-gdrive-fuse/src/fs.es6.js:400:14)

**Comment by saqebakhter** [comment]
Also noticed duplicated folders being created....

**Comment by saqebakhter** [comment]
Here's another error slightly different / different line number

2015-9-10T11:36::49 - info: adding a new file Arrow - S03E07 - Draw Back Your Bow Bluray-720p.mkv to folder Season 3
/root/node-gdrive-fuse/src/fs.es6.js:765
        for( let childInode of parent.children){
                                     ^
TypeError: Cannot read property 'children' of undefined

**Comment by thejinx0r** [comment]
The upload errors are unrelated to errors posted, but I am having them too now.

**Comment by thejinx0r** [comment]
The upload errors where were unrelated.
The original problem  of "ReferenceError: childInode is not defined" has already been fixed.
