### ISSUE TITLE
folder not getting created - delayed

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#77]
When you do mkdir you get an error : 

sakhter@hb-sakhter:~/gdrivefs$ mkdir Junk
mkdir: cannot create directory 'Junk': Input/output error
sakhter@hb-sakhter:~/gdrivefs$ ls -lrt

Folder not created right away: 

drwxrwxrwx   9 root root 4096 Dec 17  47207 Media
drwxrwxrwx  12 root root 4096 Jun 22  47465 Apps
drwxrwxrwx  62 root root 4096 Sep  5  47482 TVShows_Other
drwxrwxrwx  18 root root 4096 Sep  5  47482 TVShows_Finished
drwxrwxrwx  53 root root 4096 Sep  5  47482 TVShows
drwxrwxrwx 634 root root 4096 Sep  5  47482 Movies_3
drwxrwxrwx 138 root root 4096 Sep  5  47482 Movies_2
drwxrwxrwx 225 root root 4096 Sep  5  47482 Movies
drwxrwxrwx 193 root root 4096 Sep  5  47482 Indian_Movies
drwxrwxrwx 261 root root 4096 Jul 29  47564 Movies_4

Debug Log:

{"level":"debug","message":"creating folder Junk","timestamp":"2015-09-13T06:01:52.779Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-13T06:01:53.519Z"}
{"level":"debug","message":"Getting changes from Google Drive. The last change id was 630088.","timestamp":"2015-09-13T06:02:37.555Z"}

--- 1.5 minutes later - Junk folder is created 

{"level":"debug","message":"Junk is a new folder","timestamp":"2015-09-13T06:02:37.824Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-13T06:02:37.825Z"}

**Comment by thejinx0r** [comment]
This should be fixed now too.
I would also double check online on your Google Drive.

There was a bug where the folder was being created on Google Drive, but it was not being inserted in to the inode tree.
