### ISSUE TITLE
file modify/change time wrong

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#78]
The file modify/change time is wrong - which make plex continually re-scan the library - rolling back fusejs to git://github.com/thejinx0r/fusejs#48ee41ec4f998d40f47cbb7f99c37031eb8ee183 fixes the problem:

On latest commit --

sakhter@sakhter-ubuntu:stat /mnt/2TB2/gdrivefs/TVShows/xxxxxx.mkv
  File: ‘xxx.mkv’
  Size: 936000526       Blocks: 0          IO Block: 4096   regular file
Device: 28h/40d Inode: 18973       Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1969-12-31 19:00:00.000000000 -0500
Modify: 47371-12-12 03:52:27.000000000 -0500 <<<<<<<<
Change: 47371-12-12 03:56:23.000000000 -0500  <<<<<<
 Birth: -

Same file with old fusejs --

sakhter@sakhter-ubuntu:/mnt/2TB2/gdrivefs/TVShows/xxxxxxxxx$ stat 2xxxxxxx.mkv 
  File: ‘xxxxxxxx.mkv’
  Size: 936000526       Blocks: 0          IO Block: 4096   regular file
Device: 29h/41d Inode: 18973       Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: -9223372036854775808
Modify: 2015-05-27 13:17:19.000000000 -0400 <<<<<<<
Change: 2015-05-27 13:17:20.000000000 -0400 <<<<<<<<
 Birth: -

Big problem as Plex will rescan/rewnload the full library every library update.

**Comment by saqebakhter** [comment]
The following change seemed to fix it : 

diff --git a/src/file.es6.js b/src/file.es6.js
index 5ff98f4..84de29a 100644
--- a/src/file.es6.js
+++ b/src/file.es6.js
@@ -50,8 +50,8 @@ class GFile extends EventEmitter{
     this.parentid = parentid;
     this.name = name;
     this.size = size;
-    this.ctime = ctime;
-    this.mtime = mtime;
+    this.ctime = ctime/1000;
+    this.mtime = mtime/1000;
     this.permission = permission;
     this.mode = mode;
   }
diff --git a/src/folder.es6.js b/src/folder.es6.js
index 401e150..28a8395 100644
--- a/src/folder.es6.js
+++ b/src/folder.es6.js
@@ -374,8 +374,8 @@ class GFolder {
     this.id = id;
     this.parentid = parentid;
     this.name = name;
-    this.ctime = ctime;
-    this.mtime = mtime;
+    this.ctime = ctime/1000;
+    this.mtime = mtime/1000;
     this.permission = permission;
     this.children = children;
     this.mode = mode;

**Comment by thejinx0r** [comment]
Do you want to create a pull request?

**Comment by saqebakhter** [comment]
I'm going to verify it fixes Plex issues  ( rescanning library now ) and once i do i'll try to create a pull have not done that before.

**Comment by saqebakhter** [comment]
https://github.com/thejinx0r/node-gdrive-fuse/pull/79

**Comment by thejinx0r** [comment]
merged. I can't wait to get my internet back at home.

**Comment by saqebakhter** [comment]
Haha - yes, that upload error is beyond me so waiting for you to be back :)
