### ISSUE TITLE
latest fusejs - causes hang

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#82]
With the latest fusejs after scanning a large libarry - the fuse fs seems to be hung - can't even 'cd /mnt/gdrivefs' 

Rolling back to :  "fusejs": "git://github.com/thejinx0r/fusejs#48ee41ec4f998d40f47cbb7f99c37031eb8ee183" ,

Seems to help... Have you seen this issue ?

**Comment by thejinx0r** [comment]
I think I have, and I had been trying to track that down too.

On Fri, Sep 18, 2015 at 10:19 AM saqebakhter <notifications@github.com>
wrote:

> With the latest fusejs after scanning a large libarry - the fuse fs seems
> to be hung - can't even 'cd /mnt/gdrivefs'
>
> Rolling back to : "fusejs": "git://
> github.com/thejinx0r/fusejs#48ee41ec4f998d40f47cbb7f99c37031eb8ee183" ,
>
> Seems to help... Have you seen this issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/82>.
>
-- 
Eric

**Comment by saqebakhter** [comment]
If you need me to reproduce it - its fairly easy on my VPS let me know. 
I'm not sure how to debug it though.


Eric Yen wrote:
> I think I have, and I had been trying to track that down too.
>
> On Fri, Sep 18, 2015 at 10:19 AM saqebakhter <notifications@github.com>
> wrote:
>
> > With the latest fusejs after scanning a large libarry - the fuse fs 
> seems
> > to be hung - can't even 'cd /mnt/gdrivefs'
> >
> > Rolling back to : "fusejs": "git://
> > github.com/thejinx0r/fusejs#48ee41ec4f998d40f47cbb7f99c37031eb8ee183" ,
> >
> > Seems to help... Have you seen this issue ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/thejinx0r/node-gdrive-fuse/issues/82>.
> >
> -- 
> Eric
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/82#issuecomment-141470179>.
>

-- 
--Saqeb

**Comment by saqebakhter** [comment]
Any idea where it would be getting hung in fusejs ?

**Comment by thejinx0r** [comment]
Right now, I'm thinking that it would be in the DispatchOp in the
filesystem.cc. I think it's not thread safe and that it would require a
mutex. It's not ideal for performance, but it might not be a big problem
since the bottle neck is probably not going to be there.

On Wed, Sep 23, 2015, 1:00 PM saqebakhter <notifications@github.com> wrote:

> Any idea where it would be getting hung in fusejs ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/82#issuecomment-142663033>
> .
>
-- 
Eric

**Comment by saqebakhter** [comment]
Trying to 'npm install' this on osx - getting error -

../src/filesystem.cc:254:18: error: no member named 'forget_multi' in 'fuse_lowlevel_ops'


what nodejs/iojs version are you using on osx, and also on linux currently ? 
would be good to document the recommended versions in the wiki

**Comment by saqebakhter** [comment]
upgrading osxfuse works https://github.com/osxfuse/osxfuse/releases

**Comment by thejinx0r** [comment]
Thanks.
This should be finally fixed in fusejs.
