### ISSUE TITLE
repeating same message in log - corrupted inode?

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#84]
Seeing this line repeated over and over again in log file ( file was deleted from gdrive ) :+1: 

Seeing this line repeated over and over again in log file ( file was deleted from gdrive ) 

{"level":"debug","message":"saving folder tree","timestamp":"2015-09-23T18:26:04.011Z"}
{"level":"debug","message":"Finished parsing changes from google","timestamp":"2015-09-23T18:26:04.518Z"}
{"level":"debug","message":"Getting changes from Google Drive. The last change id was 642292.","timestamp":"2015-09-23T18:27:09.772Z"}
{"level":"debug","message":"There was 1 to parse","timestamp":"2015-09-23T18:27:10.188Z"}
{"level":"debug","message":"processing a file that was marked as deleted, but not preset in the inodeTree: FileNameReplaced.srt with id 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:27:10.188Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-23T18:27:10.188Z"}
{"level":"debug","message":"Finished parsing changes from google","timestamp":"2015-09-23T18:27:10.698Z"}
{"level":"debug","message":"Getting changes from Google Drive. The last change id was 642292.","timestamp":"2015-09-23T18:28:22.803Z"}
{"level":"debug","message":"There was 1 to parse","timestamp":"2015-09-23T18:28:23.219Z"}
{"level":"debug","message":"processing a file that was marked as deleted, but not preset in the inodeTree: FileNameReplaced.srt with id 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:28:23.220Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-23T18:28:23.220Z"}
{"level":"debug","message":"Finished parsing changes from google","timestamp":"2015-09-23T18:28:23.811Z"}
{"level":"debug","message":"Getting changes from Google Drive. The last change id was 642292.","timestamp":"2015-09-23T18:29:34.996Z"}
{"level":"debug","message":"There was 1 to parse","timestamp":"2015-09-23T18:29:35.446Z"}
{"level":"debug","message":"processing a file that was marked as deleted, but not preset in the inodeTree: FileNameReplaced.srt with id 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:29:35.446Z"}
{"level":"debug","message":"saving folder tree","timestamp":"2015-09-23T18:29:35.446Z"}
{"level":"debug","message":"Finished parsing changes from google","timestamp":"2015-09-23T18:29:36.032Z"}

File name was replaced from the logs - it looks like its stuck trying to process the delete... ?

**Comment by thejinx0r** [comment]
It's normal, when I would check for changes, I would look at one further
back in time, so it had been processed, but it keeps reprocessing that
change.

On Wed, Sep 23, 2015 at 2:32 PM saqebakhter <notifications@github.com>
wrote:

> Seeing this line repeated over and over again in log file ( file was
> deleted from gdrive ) [image: :+1:]
>
> Seeing this line repeated over and over again in log file ( file was
> deleted from gdrive )
>
> {"level":"debug","message":"saving folder
> tree","timestamp":"2015-09-23T18:26:04.011Z"}
> {"level":"debug","message":"Finished parsing changes from
> google","timestamp":"2015-09-23T18:26:04.518Z"}
> {"level":"debug","message":"Getting changes from Google Drive. The last
> change id was 642292.","timestamp":"2015-09-23T18:27:09.772Z"}
> {"level":"debug","message":"There was 1 to
> parse","timestamp":"2015-09-23T18:27:10.188Z"}
> {"level":"debug","message":"processing a file that was marked as deleted,
> but not preset in the inodeTree: FileNameReplaced.srt with id
> 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:27:10.188Z"}
> {"level":"debug","message":"saving folder
> tree","timestamp":"2015-09-23T18:27:10.188Z"}
> {"level":"debug","message":"Finished parsing changes from
> google","timestamp":"2015-09-23T18:27:10.698Z"}
> {"level":"debug","message":"Getting changes from Google Drive. The last
> change id was 642292.","timestamp":"2015-09-23T18:28:22.803Z"}
> {"level":"debug","message":"There was 1 to
> parse","timestamp":"2015-09-23T18:28:23.219Z"}
> {"level":"debug","message":"processing a file that was marked as deleted,
> but not preset in the inodeTree: FileNameReplaced.srt with id
> 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:28:23.220Z"}
> {"level":"debug","message":"saving folder
> tree","timestamp":"2015-09-23T18:28:23.220Z"}
> {"level":"debug","message":"Finished parsing changes from
> google","timestamp":"2015-09-23T18:28:23.811Z"}
> {"level":"debug","message":"Getting changes from Google Drive. The last
> change id was 642292.","timestamp":"2015-09-23T18:29:34.996Z"}
> {"level":"debug","message":"There was 1 to
> parse","timestamp":"2015-09-23T18:29:35.446Z"}
> {"level":"debug","message":"processing a file that was marked as deleted,
> but not preset in the inodeTree: FileNameReplaced.srt with id
> 0B_SCJY8yONoyWlZ1OEE2M2tEQzA","timestamp":"2015-09-23T18:29:35.446Z"}
> {"level":"debug","message":"saving folder
> tree","timestamp":"2015-09-23T18:29:35.446Z"}
> {"level":"debug","message":"Finished parsing changes from
> google","timestamp":"2015-09-23T18:29:36.032Z"}
>
> File name was replaced from the logs - it looks like its stuck trying to
> process the delete... ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/84>.
>
-- 
Eric
