### ISSUE TITLE
Error on rename

### ISSUE THREAD

**Issue by tpmckenzie** [thejinx0r/node-gdrive-fuse#85]
When sonnar attempts to rename a file I get the following error and node-gdrive-fuse crashes.

```
/root/node-gdrive-fuse/src/fs.es6.js:723
            if (child.name === oldName){
                     ^

TypeError: Cannot read property 'name' of undefined
    at GDriveFS.rename (/root/node-gdrive-fuse/src/fs.es6.js:723:22)
```

**Comment by thejinx0r** [comment]
Thanks for opening an issue.
I have already come across this issue and fixed it, but it's in a separate branch.

It will get pushed tomorrow, as it's mixed in with a big refactor of the upload mechanism.
